TS narrowing is drunk
Fixes
 error TS2339: Property 'error' does not exist on type 'SafeParseReturnType<NextConfig, NextConfig>'.
  Property 'error' does not exist on type 'SafeParseSuccess<NextConfig>'.

1021         const [errorMessages, shouldExit] = normalizeZodErrors(state.error)